In [ ]:
paragraph = "i love india. i love to play cricket"

In [ ]:
words = paragraph.lower().split()
print(words)

#for i, word in enumerate(words):
  #print(i,word)

['i', 'love', 'india.', 'i', 'love', 'to', 'play', 'cricket']


In [ ]:
import numpy as np
def word2onehot(word_ind,vector):
  #word_vec = np.zeros(vector,dtype=int)
  word_vec = [0 for i in range(vector)]
  word_index = [i for i in range(vector)]
  word_indexi = word_index[word_ind]
  word_vec[word_indexi] = 1
  return word_vec

target_word_veclist = []
for i,word in enumerate(words):
  target_word_vec = word2onehot(i,len(words))
  target_word_veclist.append(target_word_vec)
print(target_word_veclist)
#target_word_veclist = np.asarray(target_word_veclist)
#print(target_word_veclist)

[[1, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 1]]


In [ ]:
dict = {}
for i in range(len(words)):
  target_word = words[i]
  if target_word not in dict:
    context_word = []
    for j in range(i,len(words)):
      if target_word == words[j] and j!=len(words)-1:
        context_word.append(target_word_veclist[j+1])
    dict[target_word] = context_word
print(dict)

max_length = max([len(i) for i in dict.values()])
print(max_length)

extend_with_zero = [0 for i in range(len(words))]
special_char = [1 for i in range(len(words))]
for i in dict.keys():
  if len(dict[i])==0:
    dict[i].append(special_char)
  if len(dict[i])<max_length:
    for j in range(max_length-1):
      if len(dict[i])<max_length:
        dict[i].append(extend_with_zero)
print(dict)

max_length = max([len(i) for i in dict.values()])
print(max_length)

{'i': [[0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0]], 'love': [[0, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0]], 'india.': [[0, 0, 0, 1, 0, 0, 0, 0]], 'to': [[0, 0, 0, 0, 0, 0, 1, 0]], 'play': [[0, 0, 0, 0, 0, 0, 0, 1]], 'cricket': []}
2
{'i': [[0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0]], 'love': [[0, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0]], 'india.': [[0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], 'to': [[0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0]], 'play': [[0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0]], 'cricket': [[1, 1, 1, 1, 1, 1, 1, 1], [0, 0, 0, 0, 0, 0, 0, 0]]}
2


In [ ]:
import numpy as np
x = np.ones([10,20])
count = 0
lst = []
for i in x:
  count = 0
  for j in i:
    count+=j
  lst.append(count)
print(lst)

lst1 = [[1,2,3,4,5],[6,7,8,9,10],[2,3,4,5,6],[0,0,0,0,0,0],[1,1,1,1,1,1],[3,3,3,3,3,3]]
x = []
for i in range(1,len(lst1),3):
  vari = lst1[i-1]+lst1[i]
  x.append(vari)
print(x)

[20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0]
[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]]


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential,Model
from tensorflow.keras.layers import Dense,Input
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor

In [ ]:
import numpy as np
x = np.array(list(dict.values()))
x = x.reshape(x.shape[0],x.shape[1]*x.shape[2])
print(x.shape)
print(x)
print(len(x))
print(x[0])
print(len(x[0]))
#for i in range(1,len(var),max_length):
  #add = var[i-1]+var[i]
  #x.append(add)
#print(x)
#print(len(x))
#print(len(x[0]))

create_y = [target_word_veclist[words.index(i)] for i in dict.keys() if i in words]
y=[]
for i in create_y:
  var_y = i+extend_with_zero*(max_length-1)
  y.append(var_y)
y = np.array(y)
print(y.shape)
print(y)
print(len(y))
print(len(y[0]))

(6, 16)
[[0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]]
6
[0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
16
(6, 16)
[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]]
6
16


In [ ]:
input = Input(shape=(len(x[0]),))
hidden_layer1 = Dense(200,activation='relu')(input)
output = Dense(len(x[0]),activation='softmax')(hidden_layer1)
#whenonly one dense layer with 2 neurons we got loss:11.5 and acc:16.8
                              #12,9,7,4 we got loss:10.7 and acc:16.8

word2vec = Model(input,output)
word2vec.compile(loss='mse',optimizer='adam',metrics=['accuracy'])
word2vec.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 16)]              0         
                                                                 
 dense (Dense)               (None, 200)               3400      
                                                                 
 dense_1 (Dense)             (None, 16)                3216      
                                                                 
Total params: 6,616
Trainable params: 6,616
Non-trainable params: 0
_________________________________________________________________


In [ ]:
h = word2vec.fit(x,y,epochs=10,verbose=1)
                 #batch_size=2)

Epoch 1/10
1/1 [==============================] - 0s 401ms/step - loss: 0.0586 - accuracy: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 8ms/step - loss: 0.0583 - accuracy: 0.1667
Epoch 3/10
1/1 [==============================] - 0s 5ms/step - loss: 0.0579 - accuracy: 0.1667
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 0.0575 - accuracy: 0.1667
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 0.0571 - accuracy: 0.3333
Epoch 6/10
1/1 [==============================] - 0s 3ms/step - loss: 0.0566 - accuracy: 0.3333
Epoch 7/10
1/1 [==============================] - 0s 4ms/step - loss: 0.0562 - accuracy: 0.3333
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: 0.0557 - accuracy: 0.3333
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 0.0552 - accuracy: 0.3333
Epoch 10/10
1/1 [==============================] - 0s 9ms/step - loss: 0.0546 - accuracy: 0.3333


In [ ]:
import random
def test_function(words,word,context_word):
  testing_vector = []
  for i in words:
    if word == i:
      testing_vector = [(x[words.index(i)])]
    else:
      testing_vector.append([random.randint(0,1) for i in range(len(x[0]))])
      break
  return testing_vector

print(test_function(list(dict.keys()),'love',x))

[[1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0]]


In [ ]:
def test_function2(dict_keys,word,context_word_vec):
  testing_vector = []
  if word.lower() in dict_keys:
    testing_vector.append(x[dict_keys.index(word.lower())])
  else:
    vector_for_newword = [0 for j in range(len(x[0]))]
    testing_vector.append(vector_for_newword)
  return np.array(testing_vector)
print(test_function2(list(dict.keys()),'cricket',x))

[[1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]]


In [ ]:
vec1 = word2vec.predict((test_function2(list(dict.keys()), 'Love', x)))
vec2 = word2vec.predict((test_function2(list(dict.keys()), 'afnan', x)))

vec3 = word2vec.predict((test_function(list(dict.keys()), 'India', x)))
vec4 = word2vec.predict((test_function(list(dict.keys()), 'afnan', x)))

import numpy as np
def euclidian_dist(vector1,vector2):
  sum_sq = np.sum(np.square(vector1-vector2))
  return np.sqrt(sum_sq)
print(euclidian_dist(vec1,vec2))
print(euclidian_dist(vec3,vec4))

0.041682716
0.07626887


In [ ]:
#print(len([1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]))
prediction = word2vec.predict([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])

In [ ]:
prediction

array([[0.        , 0.        , 0.08344866, 0.        , 0.        ,
        0.0274223 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.07917749, 0.        , 0.        , 0.02052977,
        0.        ]], dtype=float32)

In [ ]:
#print(word2vec.get_weights()[0])
print(word2vec.trainable_variables)
print(len(word2vec.trainable_variables))

[<tf.Variable 'dense/kernel:0' shape=(16, 200) dtype=float32, numpy=
array([[-0.04480243, -0.00901143,  0.02670717, ...,  0.04568736,
        -0.15558688, -0.1198903 ],
       [-0.04448597,  0.07886937, -0.02792422, ...,  0.04670322,
         0.00305914,  0.15426542],
       [-0.12402148, -0.01533036, -0.04120564, ...,  0.06875511,
         0.12551817,  0.0765729 ],
       ...,
       [ 0.12087016, -0.04095189,  0.00270812, ..., -0.08942108,
        -0.15044212, -0.1454787 ],
       [ 0.14292945, -0.02367727,  0.14315169, ..., -0.00434931,
         0.12155439,  0.09764136],
       [ 0.08515863,  0.1378868 ,  0.10266893, ...,  0.08818783,
        -0.08841197, -0.11159925]], dtype=float32)>, <tf.Variable 'dense/bias:0' shape=(200,) dtype=float32, numpy=
array([ 0.00984882, -0.00822876,  0.00996467,  0.00956661,  0.00935601,
        0.00950655, -0.00890041, -0.00964399, -0.00660245,  0.00742284,
        0.00941578, -0.01005297, -0.0098901 , -0.00934142, -0.00961094,
       -0.0095549 , -0

In [ ]:
var1 = word2vec.get_weights()[0]*[[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]]
var2 = word2vec.get_weights()[1]*var1
var3 = word2vec.get_weights()[3]*var2
var4 = word2vec.get_weights()[4]*var3

ValueError: ignored